export const MOTIVATIONAL_QUOTES = [
  "Her gün bir öncekinden daha güçlüsün.",
  "Bugün zorsa, yarın daha kolay olacak.",
  "Kendine inanmak, başarının yarısıdır.",
  "Küçük adımlar, büyük değişimler yaratır.",
  "Vazgeçmek yok, mola vermek var.",
  "Zorluklar seni daha güçlü yapıyor.",
  "Bugün kendine iyi bak, yarın daha iyi olacak.",
  "Her 'hayır' dediğinde, özgürlüğüne 'evet' diyorsun.",
  "Geçmiş seni tanımlamaz, bugünkü kararların tanımlar.",
  "Başaramayacağını düşündüğün şeyi başardığında, kendine olan inancın artar.",
  "Bir günde bir adım, bir yılda 365 adım eder.",
  "Kendini sevmek, iyileşmenin ilk adımıdır.",
  "Bugün zor olsa da, yarın daha iyi olacak.",
  "Bağımlılık zincirlerini kırmak, özgürlüğün kapısını açar.",
  "Her temiz gün, yeni bir başlangıçtır.",
  "Düştüğün yerden kalkabilme cesareti, başarının anahtarıdır.",
  "Kendine olan inancını kaybetme, sen bunu yapabilirsin!",
  "Bugün kendine gurur duyacağın bir şey yap.",
  "Değişim zordur, ama pişmanlıktan daha kolaydır.",
  "Seni hasta eden şeyi bırakmak, en iyi ilaçtır.",
  "Kanka, sen bunu yaparsın! Her gün biraz daha iyiye.",
  "Hayat kısa, bağımlılıklarla harcayacak zamanın yok.",
  "Bugün 'hayır' dediğin her şey, yarın için bir 'evet'tir.",
  "Zorluklardan kaçmak yerine, onlarla yüzleş ve büyü.",
  "Bir gün bile önemlidir. Bugünü temiz geçir.",
  "Bağımlılık geçici bir rahatlama, özgürlük kalıcı bir mutluluktur.",
  "Kendine iyi bak, çünkü sen değerlisin.",
  "Her yeni gün, yeni bir başlangıçtır.",
  "Güçlü olmak zorunda değilsin, sadece vazgeçmemen yeterli.",
  "Bugün kendine gurur duyacağın bir şey yap.",
];